# specify language and version
language: python
python:
  - "3.6"

# which branches to run CI on
branches:
  only:
  - master
  - test_ci

# command to install dependencies
install:
  - pip install .

# command to test examples and then run tests
script:
  - pytest examples/
  - pytest --cov=mypack tests/
  - cd docs/
  - make html
