# specify language and version
language: python
python:
  - "3.6"

# which branches to run CI on
branches:
  only:
  - master
  - test_ci

# command to install dependencies
install:
  - pip install .

# set up the display port to generate figures
#     https://docs.travis-ci.com/user/gui-and-headless-browsers/#using-xvfb-directly
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

# command to test examples and then run tests
script:
  - pytest examples/
  - pytest --cov=mypack tests/
