# specify language and version
language: python
python:
  - "3.6"

# which branches to run CI on
branches:
  only:
  - master
  - test_ci

# set up the display for saving our images
#    https://docs.travis-ci.com/user/gui-and-headless-browsers/
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

# command to install dependencies
install:
  - pip install .

# command to run tests and examples
script:
  - pytest --cov=mypack
